# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Maven Jar Publish
      # You may pin to the exact commit or the version.
      # uses: eric2788/maven-jar-publish@60eda097610b2d5e98c046c1e4ead01a28bd94a6
      uses: eric2788/maven-jar-publish@v2
      with:
        # the java version to build (if not provied, it will use the ${ maven.compiler.target } properties
        java-version: NONE
        # the location of pom.xml (to build)
        locate: .
        # the module path that to upload the artifact. (the module name must same as the module path)
        upload-module: .
    - name: javadoc-cleanup
      # You may pin to the exact commit or the version.
      # uses: cicirello/javadoc-cleanup@ef23269b3b39f8d71200f09a8c183db37dea1426
      uses: cicirello/javadoc-cleanup@v1.3.2
      with:
        # The path to the root of the website
        path-to-root: .
